# docker-compose.yml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 8360:8360
    volumes:
      - ${PWD}/data:/app/data
    environment:
      TZ: 'Asia/Shanghai'
      SQLITE_PATH: '/app/data'
      JWT_TOKEN: 'VgwPHLxkRUZfIl81QJO29zE7pK60nTFd'
      SITE_NAME: 'LittleMioのBlog'
      SITE_URL: 'https://blog.littlebell.top'
      SECURE_DOMAINS: 'littlebell.top'
      AUTHOR_EMAIL: 'hoyo-os@outlook.com'
